export type ContentKind = "news" | "article" | "video";

export type ContentItem = {
  id: string;
  title: string;
  description: string;
  url: string;
  thumbnail?: string;
  publishedAt: string;
  source: string;
  kind: ContentKind;
  autoGenerated?: boolean;
};

export type VideoItem = ContentItem & {
  kind: "video";
  embedUrl: string;
};

export type ContentCacheBucket = {
  items: ContentItem[] | VideoItem[];
  sources: string[];
  fetchedAt: string;
};

export type ContentTimestamp = {
  news: string;
  videos: string;
  articles: string;
};

export type IngestResult = {
  news: ContentCacheBucket;
  videos: ContentCacheBucket;
  articles: ContentCacheBucket;
  timestamp: ContentTimestamp;
};
